### ISSUE TITLE
Zero-shot-learning issue with MixAtis

### ISSUE THREAD

**Issue by zjc664656505** [waynewu6250/LABAN#2]
Hello authors,

We are experimenting your project and trying to run the multi-intent zsl on mixatis data. But we always meet such kind of issue:Traceback (most recent call last):
  File "bert_laban.py", line 473, in <module>
    fire.Fire()
  File "/home/junchen/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/junchen/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/junchen/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "bert_laban.py", line 167, in train
    for (captions_t, labels, masks) in val_loader:
  File "/home/junchen/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/junchen/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/junchen/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/junchen/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/junchen/LABAN-main/all_data.py", line 35, in __getitem__
    labels = t.zeros(self.num_labels).scatter_(0, label, 1)
RuntimeError: index 13 is out of bounds for dimension 0 with size 13
after 1 training epoch using the ratio and num you give.

Could you help us to resolve this issue.

Thanks.

**Comment by waynewu6250** [comment]
Hi, make sure you run bert_zsl.py for zero-shot detection (set is_zero_shot=True in config.py). bert_laban.py is for normal multi-intent detection only (set is_zero_shot=False in config.py). The data is parsed differently for these two settings.

**Comment by zjc664656505** [comment]
Thanks, it works now.
